### ISSUE TITLE
Cleaning up "draggable"

### ISSUE THREAD

**Issue by gbreeze** [Bernardo-Castilho/dragdroptouch#1]
Hi Bernardo, nice work!

I have one issue:
If you go to: http://sslweb.azurewebsites.net/
1) click the bottom left icon (sort)
2) drag and drop a list-item to manually sort the list
3) click again the bottom left icon to disable sorting

Result on phones (tested on android and windows phone)
- still possible to drag an item
- scrolling on the list is broken

I guess there is something wrong with the event cleanup. In the list you can find items like 
`<div class="win-itembox" draggable="true">`. The draggable attribute will be removed by clicking the 'disable sorting' icon. 

How can I access the 'DragDropTouch' object on the '.win-itembox' element to do some cleanup?

Best Regards,
George

**Comment by Bernardo-Castilho** [comment]
Hi George

Glad you like the library.

I inspected your sample app on my Google Nexus and I think I see what the problem is. The DragDropTouch code is looking for the presence of the "draggable" attribute, not to its value. This is a bug. I thought draggable worked like "disabled" or "required", but it does not. The attribute can be set to true or to false.

I will review the code and apply a fix ASAP.

Thanks a lot for reporting this issue.

In the meantime, if you don't want to wait, perhaps you could try removing the draggable attribute from the elements instead of setting it to false. That should fix the problem. Hopefully...

**Comment by gbreeze** [comment]
Hi Bernardo, you are right, removing the attribute solves the issue and everything works fine now. 
Thanks a lot!

**Comment by Bernardo-Castilho** [comment]
That was quick! Thanks for the feedback.

Very nice app by the way. I have to start playing with Aurelia sometime soon...

**Comment by gbreeze** [comment]
`'e.draggable'`, elegant fix, mine was not so short ;-), Thanks!

**Comment by Bernardo-Castilho** [comment]
Thank *you* for helping me improve the library.
