### ISSUE TITLE
you may now publish your module as an NPM package

### ISSUE THREAD

**Issue by rozek** [Bernardo-Castilho/dragdroptouch#42]
Hello Bernardo,

your merge was really fast! Thanks a lot!

Now, that you have a `package.json`, you may also publish your module as an NPM package.

There **IS** already such a publication called `drag-drop-touch` - but, it seems to have been prepared by somebody else (although I don't know by whom). That publication also lacks any reference to this Github repo and to the ReadMe file.

Nevertheless, that package is extremely popular (more than 1000 downloads/week)

I have no idea whether you are allowed to overwrite the package with your new version. If so, you should apply the following changes to `package.json`

* change the `name` to `drag-drop-touch`
* change the version to s.th. higher than `1.3.1`

`npm publish` will then publish your module

Alternatively, you may publish your code with the `package.json` I provided to you (name `dragdroptouch`, version `1.0.0`)

If you like, I may also provide the `package.json` I described before.

With greetings from Germany,

Andreas Rozek

**Comment by Bernardo-Castilho** [comment]
Hi Andreas

>>>>>
Nevertheless, that package is extremely popular (more than 1000 downloads/week)
>>>>>

Wow, I hadn’t seen that! Pretty popular indeed.

But I don’t think I can overwrite it, it was created by someone else and apparently has been maintained by that person.

I prefer not to publish this to nmp since there are already a few copies out there, and I am not actively maintaining it these days.

I do have a TypeScript version of the package, attached here for your convenience in case you’re interested.

The file has some simple dependencies that should be trivial to remove.

>>>>>
With greetings from Germany
>>>>>

And greetings from Brazil!




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Andreas ***@***.***>
Sent: Monday, June 14, 2021 11:02 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [Bernardo-Castilho/dragdroptouch] you may now publish your module as an NPM package (#42)


Hello Bernardo,

your merge was really fast! Thanks a lot!

Now, that you have a package.json, you may also publish your module as an NPM package.

There IS already such a publication called drag-drop-touch - but, it seems to have been prepared by somebody else (although I don't know by whom). That publication also lacks any reference to this Github repo and to the ReadMe file.

Nevertheless, that package is extremely popular (more than 1000 downloads/week)

I have no idea whether you are allowed to overwrite the package with your new version. If so, you should apply the following changes to package.json

  *   change the name to drag-drop-touch
  *   change the version to s.th. higher than 1.3.1

npm publish will then publish your module

Alternatively, you may publish your code with the package.json I provided to you (name dragdroptouch, version 1.0.0)

If you like, I may also provide the package.json I described before.

With greetings from Germany,

Andreas Rozek

**Comment by rozek** [comment]
Hello Bernardo,

thanks for the immediate response!

Your attachment seems to got lost (at least, it is not shown in Github notifications). If you like, you may send it by email directly to A.Rozek@gmx.de

With greetings from Germany,

Andreas Rozek
