### ISSUE TITLE
Contributing changes

### ISSUE THREAD

**Issue by Pomax** [Bernardo-Castilho/dragdroptouch#68]
Heya,

I was trying to use this library and ended up forking it and "massaging" it a little, possibly more than you'd like, maybe exactly as much as you'd wish you had time to do, so: I have a fork up over on https://github.com/Pomax/dragdroptouch that I wouldn't mind filing as an upstream contribution if you think that's a good idea.

Some of the major changes include:

- it has a build system now (using [esbuild](https://esbuild.github.io/)), compiling a `drag-drop-touch.esm.js` and `drag-drop-touch.esm.min.js`.
- on that note, it compiles an ESM file, because it's 2024 and I want to be part of the solution =D
- the demo page got leaned up, maybe too much for your liking, but as a random drive-by user I have no interesting in wijmo, so the only example that still exists is the box example because if that works, anything works.
- it looks for an "autoload" parameter (when loaded on its own), which just immediately builds a singleton instance so that "things just work(tm)" rather than someone needing to still call `new DragDropTouch()`.
- I removed the "supportsPassive" check because it's 2024 and everything does =)
- I replaced a few loops with different/more modern loops
- There is a piece of code that had `// Added by NDP  OK? TODO` and reading over it, it wasn't OK in that it first returned if some condition was false, then followed that up with an `if` statement that could never be true. So that got changed.
 
Let me know what you'd like me to do here (happy to just keep it a fork, but even happier to get everything landed upstream of course =D).

(there is one wonky bit, where touch-dragging the box with an image doesn't do quite the right thing, but that's something that should be relatively "easy" to fix as part of the upstreaming)

**Comment by Bernardo-Castilho** [comment]
Hello Pomax

I've invited you to collaborate on the project, so you can apply the changes yourself if you don't mind.

I haven't had time to work on this in a very long while, seems like you are on top of things...

Hope you can help keep the project useful and relevant!

Thanks!
________________________________
From: Pomax ***@***.***>
Sent: Thursday, July 4, 2024 10:35 PM
To: Bernardo-Castilho/dragdroptouch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bernardo-Castilho/dragdroptouch] Contributing changes (Issue #68)


Heya,

I was trying to use this library and ended up forking it and "massaging" it a little, possibly more than you'd like, maybe exactly as much as you'd wish you had time to do, so: I have a fork up over on https://github.com/Pomax/dragdroptouch that I wouldn't mind filing as an upstream contribution if you think that's a good idea.

Some of the major changes include:

  *   it has a build system now, compiling a drag-drop-touch.esm.js and drag-drop-touch.esm.min.js.
  *   on that note, it compiles an ESM file, because it's 2024 and I want to be part of the solution =D
  *   the demo page got leaned up, maybe too much for your liking, but as a random drive-by user I have no interesting in wijmo, so the only example that still exists is the box example because if that works, anything works.
  *   it looks for an "autoload" parameter (when loaded on its own), which just immediately builds a singleton instance so that "things just work(tm)" rather than someone needing to still call new DragDropTouch().
  *   I removed the "supportsPassive" check because it's 2024 and everything does =)
  *   I replaced a few loops with different/more modern loops
  *   There is a piece of code that had // Added by NDP OK? TODO and reading over it, it wasn't OK in that it first returned if some condition was false, then followed that up with an if statement that could never be true. So that got changed.

Let me know what you'd like me to do here (happy to just keep it a fork, but even happier to get everything landed upstream of course =D).

**Comment by Pomax** [comment]
Cheers! I'll probably tag you on some things for opinions still though, because getting completely sidelined is no fun =D

**Comment by Bernardo-Castilho** [comment]
That's perfect, thanks a million!


________________________________

**Comment by Pomax** [comment]
Not to create the impression I've just walked away here, I'm actually wrapping up a bunch of work over on https://github.com/Pomax/custom-file-tree including adding integration testing using playwright, which would be fantastic to add here as well, and is the project I was working on that made me find this library in the first place =D

**Comment by Bernardo-Castilho** [comment]
Sounds awesome Mr Pomax !

Are you really from Vancouver Island? I was there a couple of times, loved it! Camped on a beach, pretty wild... 😉

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Pomax** [comment]
Pretty sure I am =D 

https://pomax.gitlab.io/birds-between-the-lakes-north-east-of-duncan-bc/

**Comment by Pomax** [comment]
Man that always takes longer than you want (decades of dev work and I still can't timebox properly). That's v3 of `<file-tree>` released, but the interesting part for this library is the testing aspect: using [playwright]() I've added drag and drop tests for `<file-tree>` over in https://github.com/Pomax/custom-file-tree/blob/main/tests/move.spec.js and I'm pretty sure that can be used here as well. And of course ideally that means "write tests, create a github action that runs on PRs, good to go".

**Comment by Pomax** [comment]
All changes were merged in, this issue can be closed =)
